include(
    ":app",
    ":devmenu",
    ":devmenu_contract",
    ":devmenu_deviceinfo",
    ":devmenu_settings",
    ":devmenu_buildinfo",
    ":devmenu_location",
    ":devmenu_logger",
    ":devmenu_http",
    ":devmenu_baseurl",
    ":devmenu_logcat",
    ":buildSrc"
)